# Use the focal Ubuntu image as the base
FROM debian:bullseye

# Install dependencies
RUN apt update -y
RUN apt install darkice -y

# Copy Darkice config
COPY darkice.cfg darkice.cfg

CMD ["darkice", "-c", "darkice.cfg"]
