name: Build Raspberry Pi Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Raspberry Pi image
        run: |
          sudo chmod +x ./build-pi-image.sh
          sudo ./build-pi-image.sh

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0
          name: Sonos Streaming Image - v1.0
          body: |
            Automated build of the Sonos streaming image.
            Build date: ${{ github.event.repository.updated_at }}
          files: |
            pi-gen/deploy/*.img.xz
          draft: false
          prerelease: false
